spring.application.name=jobmatch
# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/jobmatch_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
# Exécute schema.sql après Hibernate pour corriger les types MySQL (VARCHAR vs ENUM trop court)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# ===== SERVER =====
server.port=8086

# ===== LOGGING =====
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ESP8266ARDPROJ@gmail.com
spring.mail.password=tafdciapwfuvknqt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true