spring.application.name=jobmatch

# ===== DATABASE =====

spring.datasource.url=jdbc:mysql://localhost:3306/jobmatch_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true


# Configuration Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nadaboussabat@gmail.com
spring.mail.password=qevlmgbrgklynclx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



# ===== SERVER =====
server.port=8080

# ===== LOGGING =====
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

anthropic.api.key=
anthropic.api.url=https://api.anthropic.com/v1/messages
ml.service.url=http://localhost:8000
# ===== PUSHER CHANNELS =====

# ===== APIs (branche formations) =====
youtube.api.key=AIzaSyD1k8u7PHdMqCAwhjJfPqYDcFQX37NxJwk
google.search.api.key=AIzaSyDcIx6P9JnXGPoA6x9Og6qF7rjlua9GDSw
google.search.cx=b7d1aaecc8d074f41
gemini.api.key=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

# ===== PUSHER CHANNELS (branche main) =====
pusher.app-id=2137273
pusher.key=07a41117ca80364c7695
pusher.secret=7554b2401cf61effb94b
pusher.cluster=eu

# ===== TWILIO SMS =====
twilio.account.sid=AC7d785b997fe5bad182d133468d145277
twilio.auth.token=511bb851e6df673a6ae648ef9435c44f
twilio.messaging.service.sid=MG95d9f4f09be54827cae137d30c2f9ffb
twilio.country.code=+216
twilio.from.phone=+17405285286